### ISSUE TITLE
having floods of errors while running the command   pip install git+https://github.com/thuyen/multicrop.git.

### ISSUE THREAD

**Issue by saruarlive** [pykao/BraTS2018-tumor-segmentation#3]
Hi All,

I am having floods of errors while running the command

pip install git+https://github.com/thuyen/multicrop.git.

I am having Cuda 10.2 and  Torch Cuda version is 1.5.0.

Any suggestion on how to run the repository without errors

**Comment by pykao** [comment]
Hello Saruarlive,

I forgot the Cuda version I used in this project. But you are able to use our model through our docker hub:

https://hub.docker.com/r/pykao/brats2018/

Best,
pykao
