### ISSUE TITLE
Question regarding fusion work

### ISSUE THREAD

**Issue by sarthakpati** [pykao/BraTS2018-tumor-segmentation#5]
Hi,

I am interested in using the label fusion work you have proposed in https://www.frontiersin.org/articles/10.3389/fnins.2019.01449/full but I am not really able to figure out which portion of the code it is in. Could you please help?

I will obviously cite your work in any work I put across.

Cheers,
Sarthak

**Comment by pykao** [comment]
Hi Sarthak,

Please refer to the following repo for the label fusion work:

[Shailja's Repo](https://github.com/s-shailja/BraTS2018-tumor-segmentation)

If you have any question, feel free to email to the coauthor, S. Shailja, who primarily works on the label fusion.
